# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: swagger.doc.solstice.searking.github.com

#
# API title to appear in the user interface (Swagger).
#
title: searKing Solstice Doc Swagger API

#
# API usage restrictions.
#
usage:
  rules:
    # Allow unregistered calls for all methods.
    - selector: "*"
      allow_unregistered_calls: true

#
# HTTP rules define translation from HTTP/REST/JSON to gRPC. With these rules
# HTTP/REST/JSON clients will be able to call the DeviceManage service.
#
http:
  rules:
    #
    # HTTP/REST/JSON clients can call the 'ListShelves' method of the Bookstore
    # service using the GET HTTP verb and the '/shelves' URL path. The response
    # will the JSON representation of the 'ListShelvesResponse' message.
    #
    # Client example (Assuming your service is hosted at the given 'DOMAIN_NAME'):
    #   curl http://DOMAIN_NAME/v1/shelves
    #
    - selector: solstice.api.v1.doc.swagger.SwaggerService.Json
      get: '/doc/swagger/swagger.json'
    - selector: solstice.api.v1.doc.swagger.SwaggerService.Yaml
      get: '/doc/swagger/swagger.yaml'
    - selector: solstice.api.v1.doc.swagger.SwaggerService.UI
      get: '/doc/swagger/swagger-ui'
      additional_bindings:
        - get: '/doc/swagger/swagger-ui/index.html'
