// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.2
// source: sole/types/v1/configuration/system.proto

package configuration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type System struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// secret key to use local encryption for keeping secrets.
	// Internally, it uses the NaCl secret box algorithm to perform encryption and authentication.
	//
	// Cloud applications frequently need to store sensitive information like web API credentials or
	// encryption keys in a medium that is not fully secure.
	// See: https://gocloud.dev/howto/secrets/
	SecretKeeperUrl string `protobuf:"bytes,1,opt,name=secret_keeper_url,json=secretKeeperUrl,proto3" json:"secret_keeper_url,omitempty"`
	Go              *Go    `protobuf:"bytes,10,opt,name=go,proto3" json:"go,omitempty"` // golang configuration
}

func (x *System) Reset() {
	*x = System{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sole_types_v1_configuration_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_sole_types_v1_configuration_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_sole_types_v1_configuration_system_proto_rawDescGZIP(), []int{0}
}

func (x *System) GetSecretKeeperUrl() string {
	if x != nil {
		return x.SecretKeeperUrl
	}
	return ""
}

func (x *System) GetGo() *Go {
	if x != nil {
		return x.Go
	}
	return nil
}

type Go struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GcInterval *durationpb.Duration `protobuf:"bytes,1,opt,name=gc_interval,json=gcInterval,proto3" json:"gc_interval,omitempty"` // CGO GC Interval, 2min by default, set by forcegcperiod.
}

func (x *Go) Reset() {
	*x = Go{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sole_types_v1_configuration_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Go) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Go) ProtoMessage() {}

func (x *Go) ProtoReflect() protoreflect.Message {
	mi := &file_sole_types_v1_configuration_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Go.ProtoReflect.Descriptor instead.
func (*Go) Descriptor() ([]byte, []int) {
	return file_sole_types_v1_configuration_system_proto_rawDescGZIP(), []int{1}
}

func (x *Go) GetGcInterval() *durationpb.Duration {
	if x != nil {
		return x.GcInterval
	}
	return nil
}

var File_sole_types_v1_configuration_system_proto protoreflect.FileDescriptor

var file_sole_types_v1_configuration_system_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x73, 0x65, 0x61, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x06, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12,
	0x41, 0x0a, 0x02, 0x67, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x73, 0x65,
	0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x6f, 0x52, 0x02,
	0x67, 0x6f, 0x22, 0x40, 0x0a, 0x02, 0x47, 0x6f, 0x12, 0x3a, 0x0a, 0x0b, 0x67, 0x63, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x67, 0x63, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x4b, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x6f, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70,
	0x65, 0x63, 0x2f, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sole_types_v1_configuration_system_proto_rawDescOnce sync.Once
	file_sole_types_v1_configuration_system_proto_rawDescData = file_sole_types_v1_configuration_system_proto_rawDesc
)

func file_sole_types_v1_configuration_system_proto_rawDescGZIP() []byte {
	file_sole_types_v1_configuration_system_proto_rawDescOnce.Do(func() {
		file_sole_types_v1_configuration_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_sole_types_v1_configuration_system_proto_rawDescData)
	})
	return file_sole_types_v1_configuration_system_proto_rawDescData
}

var file_sole_types_v1_configuration_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sole_types_v1_configuration_system_proto_goTypes = []interface{}{
	(*System)(nil),              // 0: searking.sole.api.sole.types.v1.configuration.System
	(*Go)(nil),                  // 1: searking.sole.api.sole.types.v1.configuration.Go
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_sole_types_v1_configuration_system_proto_depIdxs = []int32{
	1, // 0: searking.sole.api.sole.types.v1.configuration.System.go:type_name -> searking.sole.api.sole.types.v1.configuration.Go
	2, // 1: searking.sole.api.sole.types.v1.configuration.Go.gc_interval:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sole_types_v1_configuration_system_proto_init() }
func file_sole_types_v1_configuration_system_proto_init() {
	if File_sole_types_v1_configuration_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sole_types_v1_configuration_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*System); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sole_types_v1_configuration_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Go); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sole_types_v1_configuration_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sole_types_v1_configuration_system_proto_goTypes,
		DependencyIndexes: file_sole_types_v1_configuration_system_proto_depIdxs,
		MessageInfos:      file_sole_types_v1_configuration_system_proto_msgTypes,
	}.Build()
	File_sole_types_v1_configuration_system_proto = out.File
	file_sole_types_v1_configuration_system_proto_rawDesc = nil
	file_sole_types_v1_configuration_system_proto_goTypes = nil
	file_sole_types_v1_configuration_system_proto_depIdxs = nil
}
