// Copyright 2020 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-atomicvalue -type keyCipher<*github.com/searKing/sole/app/core/crypto/pasta.Pasta>"; DO NOT EDIT.

package provider

import (
	"sync/atomic"

	"github.com/searKing/sole/pkg/crypto/pasta"
)

func _() {
	// An "cannot convert keyCipher literal (type keyCipher) to type atomic.Value" compiler error signifies that the base type have changed.
	// Re-run the go-atomicvalue command to generate them again.
	_ = (atomic.Value)(keyCipher{})
}
func (m *keyCipher) Store(value *pasta.Pasta) {
	(*atomic.Value)(m).Store(value)
}

func (m *keyCipher) Load() *pasta.Pasta {
	value := (*atomic.Value)(m).Load()
	if value == nil {
		return nil
	}
	return value.(*pasta.Pasta)
}
