// Copyright 2020 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-atomicvalue -type logger<*github.com/sirupsen/logrus.Logger>"; DO NOT EDIT.

package provider

import (
	"sync/atomic"

	"github.com/sirupsen/logrus"
)

func _() {
	// An "cannot convert logger literal (type logger) to type atomic.Value" compiler error signifies that the base type have changed.
	// Re-run the go-atomicvalue command to generate them again.
	_ = (atomic.Value)(logger{})
}
func (m *logger) Store(value *logrus.Logger) {
	(*atomic.Value)(m).Store(value)
}

func (m *logger) Load() *logrus.Logger {
	value := (*atomic.Value)(m).Load()
	if value == nil {
		return nil
	}
	return value.(*logrus.Logger)
}
