// Copyright 2020 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-atomicvalue -type proto<*github.com/searKing/sole/api/v1/viper.ViperProto>"; DO NOT EDIT.

package provider

import (
	"sync/atomic"

	"github.com/searKing/sole/api/protobuf-spec/v1/viper"
)

func _() {
	// An "cannot convert proto literal (type proto) to type atomic.Value" compiler error signifies that the base type have changed.
	// Re-run the go-atomicvalue command to generate them again.
	_ = (atomic.Value)(proto{})
}
func (m *proto) Store(value *viper.ViperProto) {
	(*atomic.Value)(m).Store(value)
}

func (m *proto) Load() *viper.ViperProto {
	value := (*atomic.Value)(m).Load()
	if value == nil {
		return nil
	}
	return value.(*viper.ViperProto)
}
