// Copyright 2020 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-atomicvalue -type sqlDB<*github.com/jmoiron/sqlx.DB>"; DO NOT EDIT.

package provider

import (
	"sync/atomic"

	"github.com/jmoiron/sqlx"
)

func _() {
	// An "cannot convert sqlDB literal (type sqlDB) to type atomic.Value" compiler error signifies that the base type have changed.
	// Re-run the go-atomicvalue command to generate them again.
	_ = (atomic.Value)(sqlDB{})
}
func (m *sqlDB) Store(value *sqlx.DB) {
	(*atomic.Value)(m).Store(value)
}

func (m *sqlDB) Load() *sqlx.DB {
	value := (*atomic.Value)(m).Load()
	if value == nil {
		return nil
	}
	return value.(*sqlx.DB)
}
