// Copyright 2020 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-atomicvalue -type systemSecret<bytes>"; DO NOT EDIT.

package provider

import "sync/atomic"

func _() {
	// An "cannot convert systemSecret literal (type systemSecret) to type atomic.Value" compiler error signifies that the base type have changed.
	// Re-run the go-atomicvalue command to generate them again.
	_ = (atomic.Value)(systemSecret{})
}

var _nil_systemSecret_bytes_value = func() (val bytes) { return }()

func (m *systemSecret) Store(value bytes) {
	(*atomic.Value)(m).Store(value)
}

func (m *systemSecret) Load() bytes {
	value := (*atomic.Value)(m).Load()
	if value == nil {
		return _nil_systemSecret_bytes_value
	}
	return value.(bytes)
}
