// Code generated by protoc-gen-go. DO NOT EDIT.
// source: viper.proto

package viper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 日志等级
type Log_Level int32

const (
	Log_panic   Log_Level = 0
	Log_fatal   Log_Level = 1
	Log_error   Log_Level = 2
	Log_warn    Log_Level = 3
	Log_warning Log_Level = 3
	Log_info    Log_Level = 4
	Log_debug   Log_Level = 5
	Log_trace   Log_Level = 6
)

var Log_Level_name = map[int32]string{
	0: "panic",
	1: "fatal",
	2: "error",
	3: "warn",
	// Duplicate value: 3: "warning",
	4: "info",
	5: "debug",
	6: "trace",
}

var Log_Level_value = map[string]int32{
	"panic":   0,
	"fatal":   1,
	"error":   2,
	"warn":    3,
	"warning": 3,
	"info":    4,
	"debug":   5,
	"trace":   6,
}

func (x Log_Level) String() string {
	return proto.EnumName(Log_Level_name, int32(x))
}

func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{3, 0}
}

// 日志格式
type Log_Format int32

const (
	Log_json Log_Format = 0
	Log_text Log_Format = 1
)

var Log_Format_name = map[int32]string{
	0: "json",
	1: "text",
}

var Log_Format_value = map[string]int32{
	"json": 0,
	"text": 1,
}

func (x Log_Format) String() string {
	return proto.EnumName(Log_Format_name, int32(x))
}

func (Log_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{3, 1}
}

type Tracing_Type int32

const (
	Tracing_urber_jaeger Tracing_Type = 0
	Tracing_zipkin       Tracing_Type = 1
)

var Tracing_Type_name = map[int32]string{
	0: "urber_jaeger",
	1: "zipkin",
}

var Tracing_Type_value = map[string]int32{
	"urber_jaeger": 0,
	"zipkin":       1,
}

func (x Tracing_Type) String() string {
	return proto.EnumName(Tracing_Type_name, int32(x))
}

func (Tracing_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{4, 0}
}

// Type specifies the type of the sampler: const, probabilistic, rateLimiting, or remote
type Tracing_Jaeger_Sampler_Type int32

const (
	Tracing_Jaeger_Sampler_const         Tracing_Jaeger_Sampler_Type = 0
	Tracing_Jaeger_Sampler_probabilistic Tracing_Jaeger_Sampler_Type = 1
	Tracing_Jaeger_Sampler_rateLimiting  Tracing_Jaeger_Sampler_Type = 2
	Tracing_Jaeger_Sampler_remote        Tracing_Jaeger_Sampler_Type = 3
)

var Tracing_Jaeger_Sampler_Type_name = map[int32]string{
	0: "const",
	1: "probabilistic",
	2: "rateLimiting",
	3: "remote",
}

var Tracing_Jaeger_Sampler_Type_value = map[string]int32{
	"const":         0,
	"probabilistic": 1,
	"rateLimiting":  2,
	"remote":        3,
}

func (x Tracing_Jaeger_Sampler_Type) String() string {
	return proto.EnumName(Tracing_Jaeger_Sampler_Type_name, int32(x))
}

func (Tracing_Jaeger_Sampler_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{4, 0, 1, 0}
}

// ViperProto is immutable, so mutex free
type ViperProto struct {
	SystemSecret         string    `protobuf:"bytes,1,opt,name=system_secret,json=systemSecret,proto3" json:"system_secret,omitempty"`
	AppInfo              *AppInfo  `protobuf:"bytes,2,opt,name=app_info,json=appInfo,proto3" json:"app_info,omitempty"`
	Service              *Service  `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Log                  *Log      `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	Tracing              *Tracing  `protobuf:"bytes,5,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Web                  *Web      `protobuf:"bytes,6,opt,name=web,proto3" json:"web,omitempty"`
	Database             *Database `protobuf:"bytes,7,opt,name=database,proto3" json:"database,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ViperProto) Reset()         { *m = ViperProto{} }
func (m *ViperProto) String() string { return proto.CompactTextString(m) }
func (*ViperProto) ProtoMessage()    {}
func (*ViperProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{0}
}

func (m *ViperProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViperProto.Unmarshal(m, b)
}
func (m *ViperProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViperProto.Marshal(b, m, deterministic)
}
func (m *ViperProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViperProto.Merge(m, src)
}
func (m *ViperProto) XXX_Size() int {
	return xxx_messageInfo_ViperProto.Size(m)
}
func (m *ViperProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ViperProto.DiscardUnknown(m)
}

var xxx_messageInfo_ViperProto proto.InternalMessageInfo

func (m *ViperProto) GetSystemSecret() string {
	if m != nil {
		return m.SystemSecret
	}
	return ""
}

func (m *ViperProto) GetAppInfo() *AppInfo {
	if m != nil {
		return m.AppInfo
	}
	return nil
}

func (m *ViperProto) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *ViperProto) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *ViperProto) GetTracing() *Tracing {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *ViperProto) GetWeb() *Web {
	if m != nil {
		return m.Web
	}
	return nil
}

func (m *ViperProto) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

type AppInfo struct {
	BuildVersion         string   `protobuf:"bytes,1,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	BuildHash            string   `protobuf:"bytes,2,opt,name=build_hash,json=buildHash,proto3" json:"build_hash,omitempty"`
	BuildTime            string   `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{1}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *AppInfo) GetBuildHash() string {
	if m != nil {
		return m.BuildHash
	}
	return ""
}

func (m *AppInfo) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

type Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{2}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Service) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Log struct {
	Level                Log_Level          `protobuf:"varint,1,opt,name=level,proto3,enum=sole.api.v1.viper.Log_Level" json:"level,omitempty"`
	Format               Log_Format         `protobuf:"varint,2,opt,name=format,proto3,enum=sole.api.v1.viper.Log_Format" json:"format,omitempty"`
	Path                 string             `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	RotationDuration     *duration.Duration `protobuf:"bytes,4,opt,name=rotation_duration,json=rotationDuration,proto3" json:"rotation_duration,omitempty"`
	RotationMaxCount     int32              `protobuf:"varint,5,opt,name=rotation_max_count,json=rotationMaxCount,proto3" json:"rotation_max_count,omitempty"`
	RotationMaxAge       *duration.Duration `protobuf:"bytes,6,opt,name=rotation_max_age,json=rotationMaxAge,proto3" json:"rotation_max_age,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{3}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLevel() Log_Level {
	if m != nil {
		return m.Level
	}
	return Log_panic
}

func (m *Log) GetFormat() Log_Format {
	if m != nil {
		return m.Format
	}
	return Log_json
}

func (m *Log) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Log) GetRotationDuration() *duration.Duration {
	if m != nil {
		return m.RotationDuration
	}
	return nil
}

func (m *Log) GetRotationMaxCount() int32 {
	if m != nil {
		return m.RotationMaxCount
	}
	return 0
}

func (m *Log) GetRotationMaxAge() *duration.Duration {
	if m != nil {
		return m.RotationMaxAge
	}
	return nil
}

type Tracing struct {
	Enable               bool            `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Type                 Tracing_Type    `protobuf:"varint,2,opt,name=type,proto3,enum=sole.api.v1.viper.Tracing_Type" json:"type,omitempty"`
	Jaeger               *Tracing_Jaeger `protobuf:"bytes,3,opt,name=jaeger,proto3" json:"jaeger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Tracing) Reset()         { *m = Tracing{} }
func (m *Tracing) String() string { return proto.CompactTextString(m) }
func (*Tracing) ProtoMessage()    {}
func (*Tracing) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{4}
}

func (m *Tracing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing.Unmarshal(m, b)
}
func (m *Tracing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing.Marshal(b, m, deterministic)
}
func (m *Tracing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing.Merge(m, src)
}
func (m *Tracing) XXX_Size() int {
	return xxx_messageInfo_Tracing.Size(m)
}
func (m *Tracing) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing proto.InternalMessageInfo

func (m *Tracing) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Tracing) GetType() Tracing_Type {
	if m != nil {
		return m.Type
	}
	return Tracing_urber_jaeger
}

func (m *Tracing) GetJaeger() *Tracing_Jaeger {
	if m != nil {
		return m.Jaeger
	}
	return nil
}

type Tracing_Jaeger struct {
	Reporter             *Tracing_Jaeger_Reporter `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	Sampler              *Tracing_Jaeger_Sampler  `protobuf:"bytes,2,opt,name=sampler,proto3" json:"sampler,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Tracing_Jaeger) Reset()         { *m = Tracing_Jaeger{} }
func (m *Tracing_Jaeger) String() string { return proto.CompactTextString(m) }
func (*Tracing_Jaeger) ProtoMessage()    {}
func (*Tracing_Jaeger) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{4, 0}
}

func (m *Tracing_Jaeger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Jaeger.Unmarshal(m, b)
}
func (m *Tracing_Jaeger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Jaeger.Marshal(b, m, deterministic)
}
func (m *Tracing_Jaeger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Jaeger.Merge(m, src)
}
func (m *Tracing_Jaeger) XXX_Size() int {
	return xxx_messageInfo_Tracing_Jaeger.Size(m)
}
func (m *Tracing_Jaeger) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Jaeger.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Jaeger proto.InternalMessageInfo

func (m *Tracing_Jaeger) GetReporter() *Tracing_Jaeger_Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *Tracing_Jaeger) GetSampler() *Tracing_Jaeger_Sampler {
	if m != nil {
		return m.Sampler
	}
	return nil
}

// Reporter configures the reporter. All fields are optional.
type Tracing_Jaeger_Reporter struct {
	// LocalAgentHostPort instructs reporter to send spans to jaeger-agent at this address
	LocalAgentHostPort   string   `protobuf:"bytes,1,opt,name=local_agent_host_port,json=localAgentHostPort,proto3" json:"local_agent_host_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Jaeger_Reporter) Reset()         { *m = Tracing_Jaeger_Reporter{} }
func (m *Tracing_Jaeger_Reporter) String() string { return proto.CompactTextString(m) }
func (*Tracing_Jaeger_Reporter) ProtoMessage()    {}
func (*Tracing_Jaeger_Reporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{4, 0, 0}
}

func (m *Tracing_Jaeger_Reporter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Jaeger_Reporter.Unmarshal(m, b)
}
func (m *Tracing_Jaeger_Reporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Jaeger_Reporter.Marshal(b, m, deterministic)
}
func (m *Tracing_Jaeger_Reporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Jaeger_Reporter.Merge(m, src)
}
func (m *Tracing_Jaeger_Reporter) XXX_Size() int {
	return xxx_messageInfo_Tracing_Jaeger_Reporter.Size(m)
}
func (m *Tracing_Jaeger_Reporter) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Jaeger_Reporter.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Jaeger_Reporter proto.InternalMessageInfo

func (m *Tracing_Jaeger_Reporter) GetLocalAgentHostPort() string {
	if m != nil {
		return m.LocalAgentHostPort
	}
	return ""
}

// Sampler allows initializing a non-default sampler.  All fields are optional.
type Tracing_Jaeger_Sampler struct {
	// server_url is the address of jaeger-agent's HTTP sampling server
	ServerUrl string                      `protobuf:"bytes,1,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Type      Tracing_Jaeger_Sampler_Type `protobuf:"varint,2,opt,name=type,proto3,enum=sole.api.v1.viper.Tracing_Jaeger_Sampler_Type" json:"type,omitempty"`
	// Param is a value passed to the sampler.
	// Valid values for Param field are:
	// - for "const" sampler, 0 or 1 for always false/true respectively
	// - for "probabilistic" sampler, a probability between 0 and 1
	// - for "rateLimiting" sampler, the number of spans per second
	// - for "remote" sampler, param is the same as for "probabilistic"
	//   and indicates the initial sampling rate before the actual one
	//   is received from the mothership.
	Param                float32  `protobuf:"fixed32,3,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Jaeger_Sampler) Reset()         { *m = Tracing_Jaeger_Sampler{} }
func (m *Tracing_Jaeger_Sampler) String() string { return proto.CompactTextString(m) }
func (*Tracing_Jaeger_Sampler) ProtoMessage()    {}
func (*Tracing_Jaeger_Sampler) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{4, 0, 1}
}

func (m *Tracing_Jaeger_Sampler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Jaeger_Sampler.Unmarshal(m, b)
}
func (m *Tracing_Jaeger_Sampler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Jaeger_Sampler.Marshal(b, m, deterministic)
}
func (m *Tracing_Jaeger_Sampler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Jaeger_Sampler.Merge(m, src)
}
func (m *Tracing_Jaeger_Sampler) XXX_Size() int {
	return xxx_messageInfo_Tracing_Jaeger_Sampler.Size(m)
}
func (m *Tracing_Jaeger_Sampler) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Jaeger_Sampler.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Jaeger_Sampler proto.InternalMessageInfo

func (m *Tracing_Jaeger_Sampler) GetServerUrl() string {
	if m != nil {
		return m.ServerUrl
	}
	return ""
}

func (m *Tracing_Jaeger_Sampler) GetType() Tracing_Jaeger_Sampler_Type {
	if m != nil {
		return m.Type
	}
	return Tracing_Jaeger_Sampler_const
}

func (m *Tracing_Jaeger_Sampler) GetParam() float32 {
	if m != nil {
		return m.Param
	}
	return 0
}

type Web struct {
	BindAddr      *Web_Net  `protobuf:"bytes,1,opt,name=bind_addr,json=bindAddr,proto3" json:"bind_addr,omitempty"`
	AdvertiseAddr *Web_Net  `protobuf:"bytes,2,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Tls           *Web_TLS  `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Cors          *Web_CORS `protobuf:"bytes,4,opt,name=cors,proto3" json:"cors,omitempty"`
	// for debug
	ForceDisableTls      bool     `protobuf:"varint,5,opt,name=force_disable_tls,json=forceDisableTls,proto3" json:"force_disable_tls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Web) Reset()         { *m = Web{} }
func (m *Web) String() string { return proto.CompactTextString(m) }
func (*Web) ProtoMessage()    {}
func (*Web) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{5}
}

func (m *Web) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Web.Unmarshal(m, b)
}
func (m *Web) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Web.Marshal(b, m, deterministic)
}
func (m *Web) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Web.Merge(m, src)
}
func (m *Web) XXX_Size() int {
	return xxx_messageInfo_Web.Size(m)
}
func (m *Web) XXX_DiscardUnknown() {
	xxx_messageInfo_Web.DiscardUnknown(m)
}

var xxx_messageInfo_Web proto.InternalMessageInfo

func (m *Web) GetBindAddr() *Web_Net {
	if m != nil {
		return m.BindAddr
	}
	return nil
}

func (m *Web) GetAdvertiseAddr() *Web_Net {
	if m != nil {
		return m.AdvertiseAddr
	}
	return nil
}

func (m *Web) GetTls() *Web_TLS {
	if m != nil {
		return m.Tls
	}
	return nil
}

func (m *Web) GetCors() *Web_CORS {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *Web) GetForceDisableTls() bool {
	if m != nil {
		return m.ForceDisableTls
	}
	return false
}

type Web_Net struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Web_Net) Reset()         { *m = Web_Net{} }
func (m *Web_Net) String() string { return proto.CompactTextString(m) }
func (*Web_Net) ProtoMessage()    {}
func (*Web_Net) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{5, 0}
}

func (m *Web_Net) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Web_Net.Unmarshal(m, b)
}
func (m *Web_Net) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Web_Net.Marshal(b, m, deterministic)
}
func (m *Web_Net) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Web_Net.Merge(m, src)
}
func (m *Web_Net) XXX_Size() int {
	return xxx_messageInfo_Web_Net.Size(m)
}
func (m *Web_Net) XXX_DiscardUnknown() {
	xxx_messageInfo_Web_Net.DiscardUnknown(m)
}

var xxx_messageInfo_Web_Net proto.InternalMessageInfo

func (m *Web_Net) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Web_Net) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Web_TLS struct {
	Enable        bool             `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	KeyPairBase64 *Web_TLS_KeyPair `protobuf:"bytes,2,opt,name=key_pair_base64,json=keyPairBase64,proto3" json:"key_pair_base64,omitempty"`
	KeyPairPath   *Web_TLS_KeyPair `protobuf:"bytes,3,opt,name=key_pair_path,json=keyPairPath,proto3" json:"key_pair_path,omitempty"`
	// service_name is used to verify the hostname on the returned
	// certificates unless InsecureSkipVerify is given. It is also included
	// in the client's handshake to support virtual hosting unless it is
	// an IP address.
	ServiceName          string   `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	AllowedTlsCidrs      []string `protobuf:"bytes,5,rep,name=allowed_tls_cidrs,json=allowedTlsCidrs,proto3" json:"allowed_tls_cidrs,omitempty"`
	WhitelistedPaths     []string `protobuf:"bytes,6,rep,name=whitelisted_paths,json=whitelistedPaths,proto3" json:"whitelisted_paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Web_TLS) Reset()         { *m = Web_TLS{} }
func (m *Web_TLS) String() string { return proto.CompactTextString(m) }
func (*Web_TLS) ProtoMessage()    {}
func (*Web_TLS) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{5, 1}
}

func (m *Web_TLS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Web_TLS.Unmarshal(m, b)
}
func (m *Web_TLS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Web_TLS.Marshal(b, m, deterministic)
}
func (m *Web_TLS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Web_TLS.Merge(m, src)
}
func (m *Web_TLS) XXX_Size() int {
	return xxx_messageInfo_Web_TLS.Size(m)
}
func (m *Web_TLS) XXX_DiscardUnknown() {
	xxx_messageInfo_Web_TLS.DiscardUnknown(m)
}

var xxx_messageInfo_Web_TLS proto.InternalMessageInfo

func (m *Web_TLS) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Web_TLS) GetKeyPairBase64() *Web_TLS_KeyPair {
	if m != nil {
		return m.KeyPairBase64
	}
	return nil
}

func (m *Web_TLS) GetKeyPairPath() *Web_TLS_KeyPair {
	if m != nil {
		return m.KeyPairPath
	}
	return nil
}

func (m *Web_TLS) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Web_TLS) GetAllowedTlsCidrs() []string {
	if m != nil {
		return m.AllowedTlsCidrs
	}
	return nil
}

func (m *Web_TLS) GetWhitelistedPaths() []string {
	if m != nil {
		return m.WhitelistedPaths
	}
	return nil
}

// a public/private key pair
type Web_TLS_KeyPair struct {
	Cert                 string   `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Web_TLS_KeyPair) Reset()         { *m = Web_TLS_KeyPair{} }
func (m *Web_TLS_KeyPair) String() string { return proto.CompactTextString(m) }
func (*Web_TLS_KeyPair) ProtoMessage()    {}
func (*Web_TLS_KeyPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{5, 1, 0}
}

func (m *Web_TLS_KeyPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Web_TLS_KeyPair.Unmarshal(m, b)
}
func (m *Web_TLS_KeyPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Web_TLS_KeyPair.Marshal(b, m, deterministic)
}
func (m *Web_TLS_KeyPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Web_TLS_KeyPair.Merge(m, src)
}
func (m *Web_TLS_KeyPair) XXX_Size() int {
	return xxx_messageInfo_Web_TLS_KeyPair.Size(m)
}
func (m *Web_TLS_KeyPair) XXX_DiscardUnknown() {
	xxx_messageInfo_Web_TLS_KeyPair.DiscardUnknown(m)
}

var xxx_messageInfo_Web_TLS_KeyPair proto.InternalMessageInfo

func (m *Web_TLS_KeyPair) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *Web_TLS_KeyPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Web_CORS struct {
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	// returns Access-Control-Allow-Origin: * if false
	UseConditional bool `protobuf:"varint,2,opt,name=use_conditional,json=useConditional,proto3" json:"use_conditional,omitempty"`
	// allowed_origins is a list of origins a cross-domain request can be executed from.
	// If the special "*" value is present in the list, all origins will be allowed.
	// An origin may contain a wildcard (*) to replace 0 or more characters
	// (i.e.: http://*.domain.com). Usage of wildcards implies a small performance penalty.
	// Only one wildcard can be used per origin.
	// Default value is ["*"]
	// return Access-Control-Allow-Origin
	AllowedOrigins []string `protobuf:"bytes,3,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	// allowed_methods is a list of methods the client is allowed to use with
	// cross-domain requests. Default value is simple methods (HEAD, GET and POST).
	AllowedMethods []string `protobuf:"bytes,4,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	// allowed_headers is list of non simple headers the client is allowed to use with
	// cross-domain requests.
	// If the special "*" value is present in the list, all headers will be allowed.
	// Default value is [] but "Origin" is always appended to the list.
	AllowedHeaders []string `protobuf:"bytes,5,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowed_headers,omitempty"`
	// exposed_headers indicates which headers are safe to expose to the API of a CORS
	// API specification
	// return Access-Control-Expose-Headers
	ExposedHeaders []string `protobuf:"bytes,6,rep,name=exposed_headers,json=exposedHeaders,proto3" json:"exposed_headers,omitempty"`
	// allow_credentials indicates whether the request can include user credentials like
	// cookies, HTTP authentication or client side SSL certificates.
	// return Access-Control-Allow-Credentials
	AllowCredentials []string `protobuf:"bytes,7,rep,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	// options_passthrough instructs preflight to let other potential next handlers to
	// process the OPTIONS method. Turn this on if your application handles OPTIONS.
	OptionsPassthrough bool `protobuf:"varint,8,opt,name=options_passthrough,json=optionsPassthrough,proto3" json:"options_passthrough,omitempty"`
	// max_age indicates how long the results of a preflight request
	// can be cached
	MaxAge *duration.Duration `protobuf:"bytes,9,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	// debug flag adds additional output to debug server side CORS issues
	Debug                bool     `protobuf:"varint,10,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Web_CORS) Reset()         { *m = Web_CORS{} }
func (m *Web_CORS) String() string { return proto.CompactTextString(m) }
func (*Web_CORS) ProtoMessage()    {}
func (*Web_CORS) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{5, 2}
}

func (m *Web_CORS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Web_CORS.Unmarshal(m, b)
}
func (m *Web_CORS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Web_CORS.Marshal(b, m, deterministic)
}
func (m *Web_CORS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Web_CORS.Merge(m, src)
}
func (m *Web_CORS) XXX_Size() int {
	return xxx_messageInfo_Web_CORS.Size(m)
}
func (m *Web_CORS) XXX_DiscardUnknown() {
	xxx_messageInfo_Web_CORS.DiscardUnknown(m)
}

var xxx_messageInfo_Web_CORS proto.InternalMessageInfo

func (m *Web_CORS) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Web_CORS) GetUseConditional() bool {
	if m != nil {
		return m.UseConditional
	}
	return false
}

func (m *Web_CORS) GetAllowedOrigins() []string {
	if m != nil {
		return m.AllowedOrigins
	}
	return nil
}

func (m *Web_CORS) GetAllowedMethods() []string {
	if m != nil {
		return m.AllowedMethods
	}
	return nil
}

func (m *Web_CORS) GetAllowedHeaders() []string {
	if m != nil {
		return m.AllowedHeaders
	}
	return nil
}

func (m *Web_CORS) GetExposedHeaders() []string {
	if m != nil {
		return m.ExposedHeaders
	}
	return nil
}

func (m *Web_CORS) GetAllowCredentials() []string {
	if m != nil {
		return m.AllowCredentials
	}
	return nil
}

func (m *Web_CORS) GetOptionsPassthrough() bool {
	if m != nil {
		return m.OptionsPassthrough
	}
	return false
}

func (m *Web_CORS) GetMaxAge() *duration.Duration {
	if m != nil {
		return m.MaxAge
	}
	return nil
}

func (m *Web_CORS) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type Database struct {
	Dsn                  string             `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxWaitDuration      *duration.Duration `protobuf:"bytes,2,opt,name=max_wait_duration,json=maxWaitDuration,proto3" json:"max_wait_duration,omitempty"`
	FailAfterDuration    *duration.Duration `protobuf:"bytes,3,opt,name=fail_after_duration,json=failAfterDuration,proto3" json:"fail_after_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Database) Reset()         { *m = Database{} }
func (m *Database) String() string { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()    {}
func (*Database) Descriptor() ([]byte, []int) {
	return fileDescriptor_982e69a07b1241d7, []int{6}
}

func (m *Database) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Database.Unmarshal(m, b)
}
func (m *Database) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Database.Marshal(b, m, deterministic)
}
func (m *Database) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Database.Merge(m, src)
}
func (m *Database) XXX_Size() int {
	return xxx_messageInfo_Database.Size(m)
}
func (m *Database) XXX_DiscardUnknown() {
	xxx_messageInfo_Database.DiscardUnknown(m)
}

var xxx_messageInfo_Database proto.InternalMessageInfo

func (m *Database) GetDsn() string {
	if m != nil {
		return m.Dsn
	}
	return ""
}

func (m *Database) GetMaxWaitDuration() *duration.Duration {
	if m != nil {
		return m.MaxWaitDuration
	}
	return nil
}

func (m *Database) GetFailAfterDuration() *duration.Duration {
	if m != nil {
		return m.FailAfterDuration
	}
	return nil
}

func init() {
	proto.RegisterEnum("sole.api.v1.viper.Log_Level", Log_Level_name, Log_Level_value)
	proto.RegisterEnum("sole.api.v1.viper.Log_Format", Log_Format_name, Log_Format_value)
	proto.RegisterEnum("sole.api.v1.viper.Tracing_Type", Tracing_Type_name, Tracing_Type_value)
	proto.RegisterEnum("sole.api.v1.viper.Tracing_Jaeger_Sampler_Type", Tracing_Jaeger_Sampler_Type_name, Tracing_Jaeger_Sampler_Type_value)
	proto.RegisterType((*ViperProto)(nil), "sole.api.v1.viper.ViperProto")
	proto.RegisterType((*AppInfo)(nil), "sole.api.v1.viper.AppInfo")
	proto.RegisterType((*Service)(nil), "sole.api.v1.viper.Service")
	proto.RegisterType((*Log)(nil), "sole.api.v1.viper.Log")
	proto.RegisterType((*Tracing)(nil), "sole.api.v1.viper.Tracing")
	proto.RegisterType((*Tracing_Jaeger)(nil), "sole.api.v1.viper.Tracing.Jaeger")
	proto.RegisterType((*Tracing_Jaeger_Reporter)(nil), "sole.api.v1.viper.Tracing.Jaeger.Reporter")
	proto.RegisterType((*Tracing_Jaeger_Sampler)(nil), "sole.api.v1.viper.Tracing.Jaeger.Sampler")
	proto.RegisterType((*Web)(nil), "sole.api.v1.viper.Web")
	proto.RegisterType((*Web_Net)(nil), "sole.api.v1.viper.Web.Net")
	proto.RegisterType((*Web_TLS)(nil), "sole.api.v1.viper.Web.TLS")
	proto.RegisterType((*Web_TLS_KeyPair)(nil), "sole.api.v1.viper.Web.TLS.KeyPair")
	proto.RegisterType((*Web_CORS)(nil), "sole.api.v1.viper.Web.CORS")
	proto.RegisterType((*Database)(nil), "sole.api.v1.viper.Database")
}

func init() {
	proto.RegisterFile("viper.proto", fileDescriptor_982e69a07b1241d7)
}

var fileDescriptor_982e69a07b1241d7 = []byte{
	// 1454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0x1b, 0xc7,
	0x11, 0x17, 0x79, 0xfc, 0x3b, 0x94, 0xa8, 0xe3, 0xa6, 0x0d, 0x58, 0x26, 0xa9, 0x2c, 0x26, 0x40,
	0x64, 0xa9, 0x3a, 0xd6, 0xaa, 0x9b, 0x22, 0x48, 0xdb, 0x40, 0x92, 0x61, 0xb8, 0xb1, 0xe2, 0x08,
	0x27, 0x35, 0x06, 0xaa, 0xba, 0x87, 0xe5, 0xdd, 0xf2, 0xb8, 0xd1, 0xf1, 0xf6, 0xb0, 0xbb, 0xa4,
	0x24, 0x3f, 0xf5, 0xb1, 0x9f, 0xa4, 0x8f, 0xfd, 0x04, 0xfd, 0x0e, 0xfd, 0x00, 0x05, 0x6a, 0xd4,
	0x6f, 0xfd, 0x16, 0xc5, 0xec, 0xed, 0x91, 0x34, 0x22, 0xda, 0x7e, 0xd0, 0x8b, 0x30, 0x9c, 0xf9,
	0xfd, 0x66, 0xf6, 0x66, 0xe7, 0xcf, 0x0a, 0x5a, 0x33, 0x9e, 0x31, 0xe9, 0x65, 0x52, 0x68, 0x41,
	0x3a, 0x4a, 0x24, 0xcc, 0xa3, 0x19, 0xf7, 0x66, 0x0f, 0x3c, 0x63, 0xe8, 0x7d, 0x11, 0x73, 0x3d,
	0x9e, 0x0e, 0xbd, 0x50, 0x4c, 0x06, 0x93, 0x2b, 0xae, 0x2f, 0xc5, 0xd5, 0x20, 0x16, 0xfb, 0x06,
	0xbf, 0x3f, 0xa3, 0x09, 0x8f, 0xa8, 0x16, 0x52, 0x0d, 0xe6, 0x62, 0xee, 0xaa, 0xf7, 0xf3, 0x58,
	0x88, 0x38, 0x61, 0x03, 0xf3, 0x6b, 0x38, 0x1d, 0x0d, 0xa2, 0xa9, 0xa4, 0x9a, 0x8b, 0x34, 0xb7,
	0xf7, 0xff, 0x5b, 0x06, 0xf8, 0x1e, 0x23, 0x9c, 0x9a, 0xc8, 0x9f, 0xc2, 0x86, 0xba, 0x51, 0x9a,
	0x4d, 0x02, 0xc5, 0x42, 0xc9, 0x74, 0xb7, 0x74, 0xaf, 0xb4, 0xd3, 0xf4, 0xd7, 0x73, 0xe5, 0x99,
	0xd1, 0x91, 0x5f, 0x43, 0x83, 0x66, 0x59, 0xc0, 0xd3, 0x91, 0xe8, 0x96, 0xef, 0x95, 0x76, 0x5a,
	0x07, 0x3d, 0xef, 0x47, 0x27, 0xf6, 0x0e, 0xb3, 0xec, 0x0f, 0xe9, 0x48, 0xf8, 0x75, 0x9a, 0x0b,
	0xe4, 0x21, 0xd4, 0x15, 0x93, 0x33, 0x1e, 0xb2, 0xae, 0xb3, 0x92, 0x75, 0x96, 0x23, 0xfc, 0x02,
	0x4a, 0x76, 0xc0, 0x49, 0x44, 0xdc, 0xad, 0x18, 0xc6, 0x87, 0xb7, 0x30, 0x4e, 0x44, 0xec, 0x23,
	0x04, 0xfd, 0x6b, 0x49, 0x43, 0x9e, 0xc6, 0xdd, 0xea, 0x4a, 0xff, 0xe7, 0x39, 0xc2, 0x2f, 0xa0,
	0xe8, 0xff, 0x8a, 0x0d, 0xbb, 0xb5, 0x95, 0xfe, 0x9f, 0xb3, 0xa1, 0x8f, 0x10, 0xf2, 0x1b, 0x68,
	0x44, 0x54, 0xd3, 0x21, 0x55, 0xac, 0x5b, 0x37, 0xf0, 0x8f, 0x6e, 0x81, 0x3f, 0xb2, 0x10, 0x7f,
	0x0e, 0xee, 0x27, 0x50, 0xb7, 0xc9, 0xc0, 0xfc, 0x0e, 0xa7, 0x3c, 0x89, 0x82, 0x19, 0x93, 0x8a,
	0x8b, 0xb4, 0xc8, 0xaf, 0x51, 0x7e, 0x9f, 0xeb, 0xc8, 0x27, 0x00, 0x39, 0x68, 0x4c, 0xd5, 0xd8,
	0x64, 0xb8, 0xe9, 0x37, 0x8d, 0xe6, 0x09, 0x55, 0xe3, 0x85, 0x59, 0xf3, 0x49, 0x9e, 0xca, 0xc2,
	0x7c, 0xce, 0x27, 0xac, 0x2f, 0xa1, 0x6e, 0x93, 0x48, 0x08, 0x54, 0x52, 0x3a, 0x61, 0x36, 0x88,
	0x91, 0xc9, 0x36, 0xac, 0x47, 0x5c, 0x65, 0x09, 0xbd, 0x09, 0x8c, 0x2d, 0x77, 0xdf, 0xb2, 0xba,
	0x67, 0x08, 0xb9, 0x07, 0xad, 0x88, 0xa9, 0x50, 0xf2, 0x0c, 0x0b, 0xc5, 0x46, 0x58, 0x56, 0x91,
	0x36, 0x94, 0x79, 0x64, 0xee, 0xa4, 0xe9, 0x97, 0x79, 0xd4, 0xff, 0x47, 0x05, 0x9c, 0x13, 0x11,
	0x93, 0xaf, 0xa0, 0x9a, 0xb0, 0x19, 0x4b, 0x4c, 0xc4, 0xf6, 0xc1, 0xc7, 0xb7, 0x5f, 0x97, 0x77,
	0x82, 0x98, 0xa3, 0xfa, 0xeb, 0x57, 0x5b, 0xce, 0xdf, 0x4a, 0x25, 0x3f, 0xe7, 0x90, 0xdf, 0x43,
	0x6d, 0x24, 0xe4, 0x84, 0x6a, 0x73, 0xa6, 0xf6, 0xc1, 0x27, 0x2b, 0xd8, 0x8f, 0x0d, 0x68, 0x41,
	0xb7, 0x2c, 0xfc, 0xda, 0x8c, 0xea, 0xb1, 0x3d, 0xaf, 0x91, 0x89, 0x80, 0x8e, 0x14, 0xda, 0x14,
	0x7c, 0x50, 0x54, 0xbe, 0xad, 0xa5, 0x9f, 0x79, 0x79, 0x6b, 0x78, 0x45, 0x6b, 0x78, 0x8f, 0x2c,
	0xe0, 0xe8, 0xf3, 0xd7, 0xaf, 0xb6, 0x3e, 0x85, 0xed, 0xbf, 0x5c, 0xec, 0xef, 0xbd, 0xf8, 0x7a,
	0xe7, 0xe2, 0x97, 0xfb, 0x5f, 0xbe, 0xd8, 0xdd, 0xf9, 0xb3, 0x97, 0x0b, 0xf7, 0xbf, 0xbe, 0xa0,
	0xfb, 0x2f, 0x5f, 0xec, 0xdd, 0xdf, 0xfb, 0xcc, 0x77, 0x0b, 0xe7, 0x05, 0x95, 0x3c, 0x04, 0x32,
	0x0f, 0x38, 0xa1, 0xd7, 0x41, 0x28, 0xa6, 0xa9, 0x36, 0xf5, 0x58, 0x3d, 0xaa, 0xbd, 0x7e, 0xb5,
	0x55, 0x76, 0xd7, 0x16, 0xac, 0x6f, 0xe9, 0xf5, 0x31, 0xda, 0x49, 0x02, 0xee, 0x1b, 0x2c, 0x1a,
	0x33, 0x5b, 0x91, 0x77, 0x71, 0xca, 0xf6, 0x52, 0xbc, 0xc3, 0x98, 0xf5, 0x43, 0xa8, 0x9a, 0x1b,
	0x20, 0x4d, 0xa8, 0x66, 0x34, 0xe5, 0xa1, 0xbb, 0x86, 0xe2, 0x88, 0x6a, 0x9a, 0xb8, 0x25, 0x14,
	0x99, 0x94, 0x42, 0xba, 0x65, 0xd2, 0x80, 0xca, 0x15, 0x95, 0xa9, 0xeb, 0x90, 0x16, 0xd4, 0x51,
	0xe2, 0x69, 0xec, 0x3a, 0xa8, 0xc6, 0xe6, 0x77, 0x2b, 0x88, 0x8d, 0xd8, 0x70, 0x1a, 0xbb, 0x55,
	0x14, 0xb1, 0xa7, 0x98, 0x5b, 0xeb, 0x95, 0xdd, 0x52, 0xff, 0x63, 0xa8, 0xe5, 0x17, 0x85, 0xe8,
	0x1f, 0x94, 0x48, 0xdd, 0x35, 0x94, 0x34, 0xbb, 0xd6, 0x6e, 0xa9, 0xff, 0xbf, 0x0a, 0xd4, 0x6d,
	0x2b, 0x92, 0x0f, 0xa1, 0xc6, 0x52, 0x3a, 0x4c, 0xf2, 0x3a, 0x6d, 0xf8, 0xf6, 0x17, 0xf9, 0x2d,
	0x54, 0xf4, 0x4d, 0xc6, 0x6c, 0x35, 0x6c, 0xad, 0x6e, 0x66, 0xef, 0xfc, 0x26, 0x63, 0x8b, 0x7a,
	0x30, 0x2c, 0xf2, 0x25, 0xd4, 0x7e, 0xa0, 0x2c, 0x66, 0xd2, 0x0e, 0x9b, 0xed, 0xb7, 0xf0, 0xbf,
	0x31, 0x40, 0xdf, 0x12, 0x7a, 0x7f, 0x77, 0xa0, 0x96, 0xab, 0xc8, 0x63, 0x68, 0x48, 0x96, 0x09,
	0xa9, 0x99, 0x34, 0xa7, 0x6b, 0x1d, 0xec, 0xbe, 0xd3, 0x8f, 0xe7, 0x5b, 0x86, 0x3f, 0xe7, 0x92,
	0x63, 0xa8, 0x2b, 0x3a, 0xc9, 0x12, 0x26, 0xed, 0xc4, 0xbc, 0xff, 0x6e, 0x37, 0x67, 0x39, 0xc1,
	0x2f, 0x98, 0xbd, 0xdf, 0x41, 0xa3, 0x70, 0x4d, 0x1e, 0xc0, 0x4f, 0x13, 0x11, 0xd2, 0x04, 0x4b,
	0x25, 0xd5, 0xc1, 0x58, 0x28, 0x1d, 0xa0, 0xc9, 0xf6, 0x3a, 0x31, 0xc6, 0x43, 0xb4, 0x3d, 0x11,
	0x4a, 0x9f, 0x0a, 0xa9, 0x7b, 0xff, 0x2a, 0x41, 0xdd, 0xfa, 0xc4, 0x19, 0x82, 0x03, 0x96, 0xc9,
	0x60, 0x2a, 0x13, 0xcb, 0x69, 0xe6, 0x9a, 0x3f, 0xca, 0x84, 0x3c, 0x7d, 0x23, 0xf5, 0xde, 0x7b,
	0x9f, 0xf5, 0xd6, 0x9b, 0xf8, 0x09, 0x56, 0x99, 0xa4, 0x13, 0x73, 0x11, 0x65, 0x3f, 0xff, 0xd1,
	0x3f, 0x82, 0x0a, 0x82, 0xb1, 0x6c, 0x42, 0x91, 0x2a, 0xed, 0xae, 0x91, 0x0e, 0x6c, 0x64, 0x52,
	0x0c, 0xe9, 0x90, 0x27, 0x5c, 0x69, 0x1e, 0xba, 0x25, 0xe2, 0xc2, 0xba, 0xa4, 0x9a, 0x9d, 0xf0,
	0x09, 0xd7, 0x58, 0x7b, 0x65, 0x02, 0x50, 0x93, 0x6c, 0x22, 0x34, 0x73, 0x9d, 0xfe, 0x67, 0xd6,
	0x87, 0x0b, 0xeb, 0x53, 0x39, 0x64, 0x32, 0xc8, 0x2f, 0xd0, 0x5d, 0x43, 0xd4, 0x4b, 0x9e, 0x5d,
	0xf2, 0xd4, 0x2d, 0xf5, 0xff, 0xdd, 0x00, 0xe7, 0xb9, 0x99, 0xdf, 0xcd, 0x21, 0x4f, 0xa3, 0x80,
	0x46, 0x51, 0x71, 0x99, 0xbd, 0xdb, 0xe7, 0xbd, 0xf7, 0x8c, 0x69, 0xbf, 0x81, 0xe0, 0xc3, 0x28,
	0x92, 0xe4, 0x10, 0xda, 0x34, 0x9a, 0x31, 0xa9, 0xb9, 0x62, 0x39, 0xbb, 0xfc, 0x4e, 0xf6, 0xc6,
	0x9c, 0x61, 0x5c, 0xfc, 0x02, 0x1c, 0x9d, 0xa8, 0xb7, 0xec, 0x3d, 0xe4, 0x9d, 0x9f, 0x9c, 0xf9,
	0x08, 0x23, 0x03, 0xa8, 0x84, 0x42, 0x2a, 0x3b, 0xa8, 0x3e, 0x5a, 0x01, 0x3f, 0xfe, 0xce, 0x3f,
	0xf3, 0x0d, 0x90, 0xec, 0x42, 0x67, 0x24, 0x64, 0xc8, 0x82, 0x88, 0x2b, 0xec, 0x9d, 0x00, 0x83,
	0x55, 0x4d, 0x37, 0x6d, 0x1a, 0xc3, 0xa3, 0x5c, 0x7f, 0x9e, 0xa8, 0xde, 0x3e, 0x38, 0xcf, 0x98,
	0x99, 0x96, 0x58, 0x34, 0xc5, 0x6e, 0x40, 0xd9, 0x4c, 0x50, 0xac, 0x21, 0xfc, 0xbc, 0xaa, 0x6f,
	0xe4, 0xde, 0x7f, 0xca, 0xe0, 0x9c, 0x9f, 0x9c, 0xad, 0xec, 0xd2, 0x6f, 0x60, 0xf3, 0x92, 0xdd,
	0x04, 0x19, 0xe5, 0x32, 0xc0, 0x6d, 0xf7, 0xc5, 0x43, 0x9b, 0x9d, 0xfe, 0xea, 0xaf, 0xf4, 0x9e,
	0xb2, 0x9b, 0x53, 0xca, 0xa5, 0xbf, 0x71, 0x99, 0x0b, 0x47, 0x86, 0x48, 0x1e, 0xc3, 0xc6, 0xdc,
	0xd7, 0x7c, 0x94, 0xbf, 0x9f, 0xa7, 0x96, 0xf5, 0x74, 0x8a, 0x53, 0x7f, 0x1b, 0xd6, 0xed, 0xf3,
	0x21, 0xdf, 0x71, 0xf9, 0xa2, 0x6a, 0x59, 0x9d, 0xd9, 0x71, 0xbb, 0xd0, 0xa1, 0x49, 0x22, 0xae,
	0x58, 0x84, 0xb9, 0x0a, 0x42, 0x1e, 0x49, 0xcc, 0x98, 0xb3, 0xd3, 0xf4, 0x37, 0xad, 0xe1, 0x3c,
	0x51, 0xc7, 0xa8, 0x26, 0x7b, 0xd0, 0xb9, 0x1a, 0x73, 0xcd, 0xb0, 0x2a, 0x59, 0x64, 0x4e, 0xa6,
	0xba, 0x35, 0x83, 0x75, 0x97, 0x0c, 0x18, 0x5a, 0xf5, 0x06, 0x50, 0xb7, 0x67, 0xc2, 0x74, 0x86,
	0x6c, 0xde, 0x92, 0x46, 0x26, 0x2e, 0x38, 0x97, 0xec, 0xc6, 0x6e, 0x5d, 0x14, 0x7b, 0xff, 0x74,
	0xa0, 0x82, 0x57, 0xb9, 0x32, 0xc3, 0x9f, 0xc3, 0xe6, 0x54, 0xb1, 0x20, 0x14, 0x69, 0xc4, 0x71,
	0x8a, 0xd3, 0xc4, 0xd0, 0x1b, 0x7e, 0x7b, 0xaa, 0xd8, 0xf1, 0x42, 0x8b, 0xc0, 0xe2, 0x9b, 0x84,
	0xe4, 0x31, 0x4f, 0xb1, 0xe0, 0xf0, 0x94, 0x6d, 0xab, 0xfe, 0x2e, 0xd7, 0x2e, 0x03, 0x27, 0x4c,
	0x8f, 0x45, 0x84, 0xa5, 0xb6, 0x0c, 0xfc, 0x36, 0xd7, 0x2e, 0x03, 0xc7, 0x8c, 0x46, 0x6c, 0x9e,
	0xa3, 0x02, 0xf8, 0x24, 0xd7, 0x22, 0x90, 0x5d, 0x67, 0x42, 0x2d, 0x01, 0xf3, 0x04, 0xb5, 0xad,
	0xba, 0x00, 0xee, 0xd9, 0xbc, 0x07, 0xa1, 0x64, 0x11, 0x4b, 0x35, 0xa7, 0x89, 0xea, 0xd6, 0xf3,
	0x5c, 0x1a, 0xc3, 0xf1, 0x42, 0x4f, 0x06, 0xf0, 0x81, 0x30, 0x0f, 0x0e, 0x15, 0x64, 0x54, 0x29,
	0x3d, 0x96, 0x62, 0x1a, 0x8f, 0xbb, 0x0d, 0xf3, 0xf5, 0xc4, 0x9a, 0x4e, 0x17, 0x16, 0x72, 0x01,
	0xf5, 0x62, 0x7d, 0x36, 0xef, 0x6c, 0x7d, 0xd6, 0x26, 0x66, 0x6d, 0xe2, 0x1c, 0x33, 0xbb, 0xae,
	0x0b, 0x26, 0x7e, 0xfe, 0xa3, 0xff, 0xd7, 0x32, 0x34, 0x8a, 0x37, 0x1f, 0xde, 0x6e, 0xa4, 0x8a,
	0x47, 0x1d, 0x8a, 0x24, 0x85, 0x0e, 0x9e, 0xe8, 0x8a, 0x72, 0xbd, 0x78, 0x80, 0x94, 0xef, 0xec,
	0x6c, 0x9b, 0x13, 0x7a, 0xfd, 0x9c, 0x72, 0x3d, 0x7f, 0x7f, 0x48, 0xf8, 0x60, 0x44, 0x79, 0x12,
	0xd0, 0x91, 0x66, 0x72, 0x11, 0xd1, 0xb9, 0xb3, 0x88, 0x1d, 0x74, 0x7f, 0x88, 0xde, 0xe7, 0xdc,
	0xfd, 0x3f, 0xed, 0x2d, 0xfd, 0x77, 0xa2, 0x18, 0x95, 0x4f, 0x79, 0x1a, 0x0f, 0xb0, 0x69, 0x07,
	0x34, 0xe3, 0x83, 0xd9, 0x83, 0x81, 0x69, 0xda, 0xaf, 0xcc, 0xdf, 0x61, 0xcd, 0x44, 0xff, 0xd5,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xa6, 0x9a, 0xb1, 0xf3, 0x0c, 0x00, 0x00,
}
