// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: viper.proto

package viper

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/golang/protobuf/ptypes/duration"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ViperProto) Validate() error {
	if this.AppInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AppInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AppInfo", err)
		}
	}
	if this.Service != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Service); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Service", err)
		}
	}
	if this.Log != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Log); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Log", err)
		}
	}
	if this.Tracing != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Tracing); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Tracing", err)
		}
	}
	if this.Web != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Web); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Web", err)
		}
	}
	if this.Database != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Database); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Database", err)
		}
	}
	return nil
}
func (this *AppInfo) Validate() error {
	return nil
}
func (this *Service) Validate() error {
	return nil
}

var _regex_Log_RotationDuration = regexp.MustCompile(`^[-+]?([0-9]*(\.[0-9]*)?[a-z]+)+$`)
var _regex_Log_RotationMaxAge = regexp.MustCompile(`^[-+]?([0-9]*(\.[0-9]*)?[a-z]+)+$`)

func (this *Log) Validate() error {
	if _, ok := Log_Level_name[int32(this.Level)]; !ok {
		return github_com_mwitkow_go_proto_validators.FieldError("Level", fmt.Errorf(`value '%v' must be a valid Log_Level field`, this.Level))
	}
	if _, ok := Log_Format_name[int32(this.Format)]; !ok {
		return github_com_mwitkow_go_proto_validators.FieldError("Format", fmt.Errorf(`value '%v' must be a valid Log_Format field`, this.Format))
	}
	if this.RotationDuration != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RotationDuration); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RotationDuration", err)
		}
	}
	if !(this.RotationMaxCount > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("RotationMaxCount", fmt.Errorf(`value '%v' must be greater than '0'`, this.RotationMaxCount))
	}
	if this.RotationMaxAge != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RotationMaxAge); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RotationMaxAge", err)
		}
	}
	return nil
}
func (this *Tracing) Validate() error {
	if _, ok := Tracing_Type_name[int32(this.Type)]; !ok {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a valid Tracing_Type field`, this.Type))
	}
	if this.Jaeger != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Jaeger); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Jaeger", err)
		}
	}
	return nil
}
func (this *Tracing_Jaeger) Validate() error {
	if this.Reporter != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Reporter); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Reporter", err)
		}
	}
	if this.Sampler != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Sampler); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Sampler", err)
		}
	}
	return nil
}
func (this *Tracing_Jaeger_Reporter) Validate() error {
	return nil
}
func (this *Tracing_Jaeger_Sampler) Validate() error {
	if _, ok := Tracing_Jaeger_Sampler_Type_name[int32(this.Type)]; !ok {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a valid Tracing_Jaeger_Sampler_Type field`, this.Type))
	}
	return nil
}
func (this *Web) Validate() error {
	if this.BindAddr != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BindAddr); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BindAddr", err)
		}
	}
	if this.AdvertiseAddr != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AdvertiseAddr); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AdvertiseAddr", err)
		}
	}
	if this.Tls != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Tls); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Tls", err)
		}
	}
	if this.Cors != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Cors); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Cors", err)
		}
	}
	return nil
}
func (this *Web_Net) Validate() error {
	return nil
}
func (this *Web_TLS) Validate() error {
	if this.KeyPairBase64 != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.KeyPairBase64); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("KeyPairBase64", err)
		}
	}
	if this.KeyPairPath != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.KeyPairPath); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("KeyPairPath", err)
		}
	}
	return nil
}
func (this *Web_TLS_KeyPair) Validate() error {
	return nil
}

var _regex_Web_CORS_MaxAge = regexp.MustCompile(`^[-+]?([0-9]*(\.[0-9]*)?[a-z]+)+$`)

func (this *Web_CORS) Validate() error {
	if this.MaxAge != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.MaxAge); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("MaxAge", err)
		}
	}
	return nil
}

var _regex_Database_MaxWaitDuration = regexp.MustCompile(`^[-+]?([0-9]*(\.[0-9]*)?[a-z]+)+$`)
var _regex_Database_FailAfterDuration = regexp.MustCompile(`^[-+]?([0-9]*(\.[0-9]*)?[a-z]+)+$`)

func (this *Database) Validate() error {
	if this.MaxWaitDuration != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.MaxWaitDuration); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("MaxWaitDuration", err)
		}
	}
	if this.FailAfterDuration != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FailAfterDuration); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FailAfterDuration", err)
		}
	}
	return nil
}
