consumes:
- application/json
definitions:
  dateDateRequest:
    properties:
      RequestId:
        type: string
    type: object
  dateDateResponse:
    properties:
      Date:
        type: string
      RequestId:
        type: string
    type: object
  protobufAny:
    additionalProperties: false
    properties:
      '@type':
        type: string
    type: object
  rpcStatus:
    properties:
      code:
        format: int32
        type: integer
      details:
        items:
          $ref: '#/definitions/protobufAny'
        type: array
      message:
        type: string
    type: object
info:
  contact:
    email: searKingChan@gmail.com
    name: sole
    url: http://github.com/searKing/sole
  title: sole
  version: 1.0.0
paths:
  /date/*path:
    get:
      description: |
        + 本接口返回服务节点当前日期
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的日期。
      operationId: DateService_Now
      parameters:
      - in: query
        name: RequestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询
      tags:
      - 日期查询
  /date/error:
    get:
      description: |
        + 本接口返回服务节点当前错误
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的错误。
      operationId: DateService_Error3
      parameters:
      - in: query
        name: RequestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询，只返回错误，测试使用
      tags:
      - 日期查询-错误
    post:
      description: |
        + 本接口返回服务节点当前错误
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的错误。
      operationId: DateService_Error4
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dateDateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询，只返回错误，测试使用
      tags:
      - 日期查询-错误
  /date/error/**:
    get:
      description: |
        + 本接口返回服务节点当前错误
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的错误。
      operationId: DateService_Error2
      parameters:
      - in: query
        name: RequestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询，只返回错误，测试使用
      tags:
      - 日期查询-错误
  /date/error/*path:
    get:
      description: |
        + 本接口返回服务节点当前错误
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的错误。
      operationId: DateService_Error
      parameters:
      - in: query
        name: RequestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询，只返回错误，测试使用
      tags:
      - 日期查询-错误
  /date/now:
    get:
      description: |
        + 本接口返回服务节点当前日期
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的日期。
      operationId: DateService_Now3
      parameters:
      - in: query
        name: RequestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询
      tags:
      - 日期查询
    post:
      description: |
        + 本接口返回服务节点当前日期
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的日期。
      operationId: DateService_Now4
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dateDateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询
      tags:
      - 日期查询
  /date/now/**:
    get:
      description: |
        + 本接口返回服务节点当前日期
        + 如果本服务运行在多个节点之上，此接口返回的日期只针对当前访问的服务节点，并不反应整个集群的日期。
      operationId: DateService_Now2
      parameters:
      - in: query
        name: RequestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/dateDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      summary: 日期查询
      tags:
      - 日期查询
produces:
- application/json
swagger: "2.0"
tags:
- name: DateService
