// Copyright 2021 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-enum -type Type -trimprefix=Type"; DO NOT EDIT.

package opentrace

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeJeager-0]
	_ = x[TypeZipkin-1]
	_ = x[TypeButt-2]
}

const _Type_name = "JeagerZipkinButt"

var _Type_index = [...]uint8{0, 6, 12, 16}

func _() {
	var _nil_Type_value = func() (val Type) { return }()

	// An "cannot convert Type literal (type Type) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_Type_value
}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}

var _Type_values = []Type{0, 1, 2}

var _Type_name_to_values = map[string]Type{
	_Type_name[0:6]:   0,
	_Type_name[6:12]:  1,
	_Type_name[12:16]: 2,
}

// ParseTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseTypeString(s string) (Type, error) {
	if val, ok := _Type_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("Type does not belong to Type values", s)
}

// TypeValues returns all values of the enum
func TypeValues() []Type {
	return _Type_values
}

// IsAType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Type) Registered() bool {
	for _, v := range _Type_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_Type_value = func() (val Type) { return }()

	// An "cannot convert Type literal (type Type) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_Type_value

	// An "cannot convert Type literal (type Type) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_Type_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Type
func (i Type) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Type
func (i *Type) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseTypeString(string(data))
	return err
}

func _() {
	var _nil_Type_value = func() (val Type) { return }()

	// An "cannot convert Type literal (type Type) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_Type_value

	// An "cannot convert Type literal (type Type) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_Type_value
}

// MarshalJSON implements the json.Marshaler interface for Type
func (i Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Type
func (i *Type) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Type should be a string, got Type", data)
	}

	var err error
	*i, err = ParseTypeString(s)
	return err
}

func _() {
	var _nil_Type_value = func() (val Type) { return }()

	// An "cannot convert Type literal (type Type) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_Type_value

	// An "cannot convert Type literal (type Type) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_Type_value
}

// MarshalText implements the encoding.TextMarshaler interface for Type
func (i Type) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Type
func (i *Type) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseTypeString(string(text))
	return err
}

//func _() {
//	var _nil_Type_value = func() (val Type) { return }()
//
//	// An "cannot convert Type literal (type Type) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_Type_value
//
//	// An "cannot convert Type literal (type Type) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_Type_value
//}

// MarshalYAML implements a YAML Marshaler for Type
func (i Type) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Type
func (i *Type) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseTypeString(s)
	return err
}

func _() {
	var _nil_Type_value = func() (val Type) { return }()

	// An "cannot convert Type literal (type Type) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_Type_value

	// An "cannot convert Type literal (type Type) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_Type_value
}

func (i Type) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Type) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// TypeSliceContains reports whether sunEnums is within enums.
func TypeSliceContains(enums []Type, sunEnums ...Type) bool {
	var seenEnums = map[Type]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// TypeSliceContainsAny reports whether any sunEnum is within enums.
func TypeSliceContainsAny(enums []Type, sunEnums ...Type) bool {
	var seenEnums = map[Type]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
