// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pasta.proto

package pasta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ViperProto is immutable, so mutex free
type ViperProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *ViperProto) Reset() {
	*x = ViperProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pasta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViperProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViperProto) ProtoMessage() {}

func (x *ViperProto) ProtoReflect() protoreflect.Message {
	mi := &file_pasta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViperProto.ProtoReflect.Descriptor instead.
func (*ViperProto) Descriptor() ([]byte, []int) {
	return file_pasta_proto_rawDescGZIP(), []int{0}
}

func (x *ViperProto) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemSecrets        [][]byte `protobuf:"bytes,1,rep,name=system_secrets,json=systemSecrets,proto3" json:"system_secrets,omitempty"`                        // new, old, older,..., oldest
	RotatedSystemSecrets [][]byte `protobuf:"bytes,2,rep,name=rotated_system_secrets,json=rotatedSystemSecrets,proto3" json:"rotated_system_secrets,omitempty"` // old, older,..., oldest
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pasta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_pasta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_pasta_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetSystemSecrets() [][]byte {
	if x != nil {
		return x.SystemSecrets
	}
	return nil
}

func (x *Secret) GetRotatedSystemSecrets() [][]byte {
	if x != nil {
		return x.RotatedSystemSecrets
	}
	return nil
}

var File_pasta_proto protoreflect.FileDescriptor

var file_pasta_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x61, 0x73, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x73,
	0x6f, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x76, 0x69, 0x70, 0x65, 0x72,
	0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x70, 0x61, 0x73, 0x74, 0x61, 0x22, 0x4c, 0x0a,
	0x0a, 0x56, 0x69, 0x70, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3e, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x76, 0x69, 0x70, 0x65, 0x72, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x70, 0x61, 0x73, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x65, 0x0a, 0x06, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0d, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x16,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x14, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x65, 0x64, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x65, 0x61, 0x72, 0x4b, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x73, 0x74, 0x61, 0x3b,
	0x70, 0x61, 0x73, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pasta_proto_rawDescOnce sync.Once
	file_pasta_proto_rawDescData = file_pasta_proto_rawDesc
)

func file_pasta_proto_rawDescGZIP() []byte {
	file_pasta_proto_rawDescOnce.Do(func() {
		file_pasta_proto_rawDescData = protoimpl.X.CompressGZIP(file_pasta_proto_rawDescData)
	})
	return file_pasta_proto_rawDescData
}

var file_pasta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pasta_proto_goTypes = []interface{}{
	(*ViperProto)(nil), // 0: sole.api.v1.viper.crypto.pasta.ViperProto
	(*Secret)(nil),     // 1: sole.api.v1.viper.crypto.pasta.Secret
}
var file_pasta_proto_depIdxs = []int32{
	1, // 0: sole.api.v1.viper.crypto.pasta.ViperProto.secret:type_name -> sole.api.v1.viper.crypto.pasta.Secret
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pasta_proto_init() }
func file_pasta_proto_init() {
	if File_pasta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pasta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViperProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pasta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pasta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pasta_proto_goTypes,
		DependencyIndexes: file_pasta_proto_depIdxs,
		MessageInfos:      file_pasta_proto_msgTypes,
	}.Build()
	File_pasta_proto = out.File
	file_pasta_proto_rawDesc = nil
	file_pasta_proto_goTypes = nil
	file_pasta_proto_depIdxs = nil
}
