// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: health.proto

// 健康监测服务 API

package health

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "google.golang.org/genproto/googleapis/api/httpbody"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AliveResponse) Validate() error {
	return nil
}
func (this *ReadyResponse) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *VersionResponse) Validate() error {
	return nil
}
